/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_malacca_archives_ArchivesPatch */

#ifndef _Included_com_malacca_archives_ArchivesPatch
#define _Included_com_malacca_archives_ArchivesPatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_malacca_archives_ArchivesPatch
 * Method:    patchByte
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_malacca_archives_ArchivesPatch_patchByte
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
